##########
# collectionbuilder-contentdm
# Jekyll Digital Collection Generator, designed as a skin over CONTENTdm
# https://github.com/CollectionBuilder/collectionbuilder-contentdm
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://www.lib.uidaho.edu
# location on the website, normally in /digital
# e.g. /digital/hjccc
baseurl: /digital/demo_lithics
# location of code, the full url to your github repository
source-code: https://github.com/uidaholib/collectionbuilder-cdm-template
# url to the shared assets folder on Digital
digital-assets: https://www.lib.uidaho.edu/assets


##########
# SITE SETTINGS
#
# title of site appears in banner
title: Crabtree Lithic Comparative Collection
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Digitizing the Donald Crabtree Flintknapping Collection in 2D and 3D
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Crabtree Lithic Technology Collection is one of the preeminent flintknapping collections in the United States. This collection includes lithic (stone) tools and artifacts created by Donald E. Crabtree as well as manuscripts and images related to his work."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: 
# Organization branding
organization-name: "Digital Initiatives, University of Idaho Library"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png


##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: demo_lithics 
# contentdm collection name, matches collection ID used by CDM
digital-objects: /digital/demo_lithics/objects/
# CONTENTdm server url
cdm-url: https://digital.lib.uidaho.edu
# page generation settings 
# "data" value must be the name of the metadata file (other values should be not be changed)
page_gen:
  - data: 'demo_lithics'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html' 
    filter: 'objectid'  

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
